"""add user_invitations table

Revision ID: 457736ebe535
Revises: 80bd2b603dd2
Create Date: 2024-09-22 16:45:29.252679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457736ebe535'
down_revision: Union[str, None] = '80bd2b603dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('token', sa.String(), nullable=False),
                    sa.Column('is_used', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.BigInteger(), nullable=True),
                    sa.Column('expires_at', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('user_invitation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitation',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('token', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_used', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', sa.BIGINT(),
                              autoincrement=False, nullable=True),
                    sa.Column('expires_at', sa.BIGINT(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], [
                        'users.id'], name='user_invitation_user_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='user_invitation_pkey')
                    )
    op.drop_table('user_invitations')
    # ### end Alembic commands ###
