"""create tables and relations

Revision ID: ba50ddae82df
Revises:
Create Date: 2024-09-21 11:24:06.929164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba50ddae82df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('personal', sa.Boolean(), nullable=True),
                    sa.Column('settings', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.BigInteger(), nullable=True),
                    sa.Column('updated_at', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('profile', sa.JSON(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('settings', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.BigInteger(), nullable=True),
                    sa.Column('updated_at', sa.BigInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('org_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['org_id'], ['organizations.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'id', 'org_id', name='unique_id_org_id'),
                    sa.UniqueConstraint(
                        'name', 'org_id', name='unique_role_in_org')
                    )
    op.create_table('member',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('org_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Integer(), nullable=False),
                    sa.Column('settings', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.BigInteger(), nullable=True),
                    sa.Column('updated_at', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['org_id'], ['organizations.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['role_id', 'org_id'], [
                        'roles.id', 'roles.org_id'], ),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['roles.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('org_id', 'user_id',
                                        name='unique_org_id_user_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    op.drop_table('roles')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
